openapi: 3.0.3
info:
  title: Gym Member API
  version: 1.0.0
  description: >
    Passport-protected APIs for Gym members. Use `POST /api/member/login` to obtain
    a Bearer token, then include it in the `Authorization` header (`Bearer <token>`).
servers:
  - url: http://127.0.0.1:8000
    description: Local (default)
  - url: http://localhost
    description: Local (hostname)
  - url: https://staging.example.com
    description: Staging server
  - url: https://example.com
    description: Production server
components:
  securitySchemes:
    PassportToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          example: member@example.com
        password:
          type: string
          format: password
          example: secret
    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Login successful.
        data:
          type: object
          properties:
            token:
              type: string
              example: 1|J5ud1...
            token_type:
              type: string
              example: Bearer
            expires_at:
              type: string
              format: date-time
            user:
              $ref: '#/components/schemas/MemberSummary'
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Validation failed.
        errors:
          type: object
          additionalProperties: true
    MemberSummary:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
          nullable: true
    Profile:
      allOf:
        - $ref: '#/components/schemas/MemberSummary'
        - type: object
          properties:
            age:
              type: integer
              nullable: true
            gender:
              type: string
              nullable: true
            address:
              type: string
              nullable: true
            status:
              type: string
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
    PaginationMeta:
      type: object
      properties:
        pagination:
          type: object
          properties:
            current_page:
              type: integer
            per_page:
              type: integer
            total:
              type: integer
            last_page:
              type: integer
            from:
              type: integer
              nullable: true
            to:
              type: integer
              nullable: true
paths:
  /api/member/login:
    post:
      tags: [Auth]
      summary: Member login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials or unauthorized role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/pages/{slug}:
    get:
      tags: [CMS]
      summary: Fetch CMS page by slug
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Page retrieved
        '404':
          description: Page not found
  /api/content/{type}:
    get:
      tags: [CMS]
      summary: Fetch content fragments by type
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Content items retrieved
  /api/member/profile:
    get:
      tags: [Member]
      summary: Get profile
      security:
        - PassportToken: []
      responses:
        '200':
          description: Profile retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Profile'
        '401':
          description: Unauthorized
    put:
      tags: [Member]
      summary: Update profile
      security:
        - PassportToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email]
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                phone:
                  type: string
                  nullable: true
                address:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Profile updated
        '422':
          description: Validation failed
  /api/member/password:
    put:
      tags: [Member]
      summary: Update password
      security:
        - PassportToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [current_password, password, password_confirmation]
              properties:
                current_password:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
      responses:
        '200':
          description: Password updated
        '422':
          description: Validation failed
  /api/member/dashboard:
    get:
      tags: [Member]
      summary: Dashboard snapshot
      security:
        - PassportToken: []
      responses:
        '200':
          description: Dashboard data
  /api/member/subscriptions:
    get:
      tags: [Member]
      summary: List subscriptions
      security:
        - PassportToken: []
      responses:
        '200':
          description: Subscriptions list
  /api/member/activities:
    get:
      tags: [Member]
      summary: Paginated activity logs
      security:
        - PassportToken: []
      parameters:
        - name: per_page
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Activities retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
  /api/member/workout-plans:
    get:
      tags: [Workout Plans]
      summary: List workout plans
      security:
        - PassportToken: []
      parameters:
        - name: per_page
          in: query
          schema:
            type: integer
        - name: status
          in: query
          schema:
            type: string
            enum: [all, active, inactive, completed]
      responses:
        '200':
          description: Workout plans
  /api/member/workout-plans/{id}:
    get:
      tags: [Workout Plans]
      summary: Show workout plan
      security:
        - PassportToken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Workout plan details
        '404':
          description: Not found
  /api/member/workout-plans/{id}/upload-video:
    post:
      tags: [Workout Plans]
      summary: Upload workout video
      security:
        - PassportToken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [video, exercise_name]
              properties:
                video:
                  type: string
                  format: binary
                exercise_name:
                  type: string
                duration_seconds:
                  type: integer
      responses:
        '200':
          description: Upload queued
        '400':
          description: Validation or ownership failure
  /api/member/workout-plans/{id}/mark-attendance:
    post:
      tags: [Workout Plans]
      summary: Mark attendance after uploads
      security:
        - PassportToken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Attendance marked
        '400':
          description: Missing uploads
  /api/member/workout-videos:
    get:
      tags: [Workout Videos]
      summary: List workout videos
      security:
        - PassportToken: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [all, pending, approved, rejected]
        - name: plan_id
          in: query
          schema:
            type: integer
        - name: per_page
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Videos retrieved
  /api/member/diet-plans:
    get:
      tags: [Diet Plans]
      summary: List diet plans
      security:
        - PassportToken: []
      parameters:
        - name: per_page
          in: query
          schema:
            type: integer
        - name: status
          in: query
          schema:
            type: string
            enum: [all, active, inactive, completed]
      responses:
        '200':
          description: Diet plans retrieved
  /api/member/check-in:
    post:
      tags: [Attendance]
      summary: Manual check-in
      security:
        - PassportToken: []
      responses:
        '200':
          description: Check-in successful
        '400':
          description: Already checked in
        '403':
          description: Subscription/workout plan missing
  /api/member/check-out:
    post:
      tags: [Attendance]
      summary: Manual check-out
      security:
        - PassportToken: []
      responses:
        '200':
          description: Checkout successful
        '400':
          description: Invalid workflow
        '403':
          description: Subscription/workout plan missing

